//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSystem.App_LocalResources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSystem.App_LocalResources.Account.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę podać hasło dla.
        /// </summary>
        public static string GivePassword {
            get {
                return ResourceManager.GetString("GivePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby kontynuowac, prosze podac PESEL.
        /// </summary>
        public static string GivePESEL {
            get {
                return ResourceManager.GetString("GivePESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli potrzebujesz pomocy, zachęcamy do kontaktu..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tutaj!.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe hasło, spróbuj jeszcze raz..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrzebujesz pomocy?.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany PESEL nie został znaleziony..
        /// </summary>
        public static string PESELNotFound {
            get {
                return ResourceManager.GetString("PESELNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL powinien składać się z 11 cyfr..
        /// </summary>
        public static string RegexPESEL {
            get {
                return ResourceManager.GetString("RegexPESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regulaminie.
        /// </summary>
        public static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL jest wymagany..
        /// </summary>
        public static string ReqPESEL {
            get {
                return ResourceManager.GetString("ReqPESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odwiedź strone rekrutacji!.
        /// </summary>
        public static string VisitRecrutationSite {
            get {
                return ResourceManager.GetString("VisitRecrutationSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcesz wiedziec wiecej?.
        /// </summary>
        public static string WantMore {
            get {
                return ResourceManager.GetString("WantMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadzając numer PESEL w powyższym formularzu godzisz się na warunki opisane w ..
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
